#!/usr/bin/python
# -*- coding: utf-8 -*-

ballots=[
{"count": 1, "ballot": [["marikenspace"], ["hackerspace nijmegen"], ["noviohack"], ["hack024"], ["hack023"], ["eos (endofstack)"], ["moenenspace"], ["backspace"]]},
{"count": 1, "ballot": [['hacktronic', 'backspace'], ['hacktag', 'noviospace'], ['hackdifferent™'], ['spektrum'], ['hacktitude'], ['hackfabrique'], ['hack inside'],
                         ['hackerspace gelderland'], ['hackatronic'], ['hacktastic'], ['hackiety'], ['hackstack'], ['hack4all'], ['nimspace'], ['noviohack'],
                         ['hack shack'], ['waalspace'], ['hackstation'], ['io-bus'], ['hackerspace nijmegen'] ]},
{"count": 1, "ballot": [["hackerij"],
                        ["hackery", "bitibyte  (bit i byte ) (bit/byte)  (bit || byte) (bit or byte)", "hack-ology", "hackers guild", "hackstack"],
                        ["<32hack", "hacklab", "hackunion"], ["hackfabriek hackfabrique", "freedom of technology", "hacktitude", "hack studio"],
                        ["hack collective", "hack institute", "hacker's habitat (hh)"], ["place in space", "hackers delight", "spectrum", "hack shack"],
                        ["hack by design", "hackersunited", "hackfabrique"], ["bots-r-us", "قرصنة هادفة", "hack4all", "digitall", "hackers paradise"]] },
{"count": 1, "ballot": [["heap"], ["h-it & run"], ["nack"], ["frickadel"], ["eos (endofstack)"], ["hackuna-matata"], ["mindsunboxed"], ["cyber-space"],
                        ["hack23"], ["hackaholics"], ["hackerspace gelderland"], ["noviohack"], ["hackstation", "hackfabrique", "haqtique", "batahackers",
                         "hackatronic", "hacktag", "hacktastic", "hack-society", "hackstitution", "hacknation", "hackstack", "hacktitude", "hackerij"]]},
{"count": 1, "ballot": [["hack-ology"], ["hacker & co"], ["waalspace"], ["moenenspace"], ["mariekenspace"], ["backspace"],
                        ["hackaholics"], ["auto-mate / automate / automates"], ["hackerspace nijmegen"], ["hackery"],
			["hackerij"], ["hackstation"], ["de herkkertjes"], ["de hackert"], ["nack"], ["nimspace"], ["nimmaspace"],
			["io-bus"], ["hackerclub"], ["hackstack"], ["eos (endofstack)"], ["stack / stek"], ["save in space"],
			["savespace"], ["frickadel"], ["spacewave"], ["h-sin"], ["alt-space"], ["alt-space"], ["hack studio"],
			["hack shack"], ["hacklab"], ["hackism"], ["tinker-studio"], ["hacktastic"], ["hacktag"], ["hack-o-l0g1c"],
			["hacker's habitat (hh)"], ["hacktogether"], ["hackfabriek hackfabrique"], ["hackfabrique"], ["place in space"],
			["hackbase"], ["key-code"], ["take a byte"], ["hack inside"], ["hack insight"], ["robot intelligence"],
			["hackers paradise"], ["freedom of technology"], ["bots-r-us"], ["heap"], ["digitall digitall"], ["digitall"],
			["batahackers"], ["hackattack"], ["cryptspace"], ["hackatronic"], ["hack2themax"], ["hacktiek haqtique"],
			["hackerbase"], ["hackers delight"], ["goffertspace"], ["noviomahack"], ["noviohack"], ["hack4all"], ["back2base"],
			["back2basics"], ["dig-it (digit & dig it & dig it)"], ["dug-out | dig-in"], ["dug-io"], ["di/og-i/o (dig-in & dug-out)"],
			["di/do (digit in & digit out)"], ["bitibyte  (bit i byte ) (bit/byte)  (bit || byte) (bit or byte)"], ["hack4love (h4l)"],
			["love2hack (l2h)"], ["hackdifferent™"], ["ideafactory024"], ["hackunited"], ["hackuna-matata"], ["hack101"],
			["mindsunboxed"], ["hacktitude"], ["h-it & run"], ["hacking4all"], ["has"], ["haas"], ["has4all"], ["has-it-all"],
			["karl marxspace"], ["marxspace"], ["hackpret"], ["hack024"], ["hack023"], ["hack23"], ["hackerspace gelderland"],
			["tinker department"], ["mind studio"], ["mind department"], ["hackers guild"], ["hackersmind"], ["hack by default"],
			["hacked by default"], ["hack by design"], ["hacked by design"], ["hackiety"], ["demolutionteam"], ["hackstitution"],
			["hacknation"], ["hackernation"], ["hackunion"], ["hackerunion"], ["hackersunited"], ["hack collective"], ["hack institute"],
			["hackers institute"], ["hackerschool"], ["hacker college"], ["hack-society"], ["pigs in space"], ["(s)hack"], ["sha©k"],
			["hut"], ["<32hack"], ["hack2<3"], ["<3-it"], ['brotherhood of "h"'], ["ctrl-alt-del"], ["cyber-space"], ["cyber-pub"],
			["cyber-bar"], ["cracklab"], ["whitespace"], ["mutare cimex"], ["industria caesim"], ["f-society"], ["project bullrun"],
			["spectrum"], ["xkeyscore"], ["قرصنة هادفة"], ["آلة حاسبة"]]},
{"count": 1, "ballot": [["xkeyscore"], ["hackuna-matata"], ["hackerspace nijmegen"], ["hackerbase"], ["spectrum"], ["hack society"], ["marxspace"],
			["'قرصنة هادفة"], ["f-society"], ["hackerspace gelderland"], ["'industria caesim_"], ["hacklab"], ["spektrum"]]},
{"count": 1, "ballot": [["hacklab"], ["hackerij"], ["f-society"], ["hacker & co"], ["hackerspace nijmegen"], ["noviohack"], ["tinker-studio", "tinker studio"]]},
{"count": 1, "ballot": [["nack"], ["heap"], ["industia caesim"], ["hackerspace nijmegen"]]},
{"count": 1, "ballot": [["hackerij"], ["hacklab"], ["f-society"], ["hacker & co"], ["hackerspace nijmegen"]]},
{"count": 1, "ballot": [["hackerspace nijmegen"], ["hackuna-matata"], ["hack023"], ["hacklab"], ["hacker collective"]]}]


